/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "comms.h"


void
article_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	char *join_1_arg1;
	int join_1_arg2;
	int  *result_2;
	char *leave_1_arg1;
	int leave_1_arg2;
	int  *result_3;
	char *subscribe_1_arg1;
	int subscribe_1_arg2;
	char *subscribe_1_arg3;
	int  *result_4;
	char *unsubscribe_1_arg1;
	int unsubscribe_1_arg2;
	char *unsubscribe_1_arg3;
	int  *result_5;
	char *publish_1_arg1;
	int publish_1_arg2;
	char *publish_1_arg3;
	int  *result_6;

#ifndef	DEBUG
	clnt = clnt_create (host, Article, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = join_1(join_1_arg1, join_1_arg2, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = leave_1(leave_1_arg1, leave_1_arg2, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = subscribe_1(subscribe_1_arg1, subscribe_1_arg2, subscribe_1_arg3, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = unsubscribe_1(unsubscribe_1_arg1, unsubscribe_1_arg2, unsubscribe_1_arg3, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = publish_1(publish_1_arg1, publish_1_arg2, publish_1_arg3, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = ping_1(clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	article_1 (host);
exit (0);
}
