/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "communicate.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
join_1(char *ip, int port,  CLIENT *clnt)
{
	join_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ip = ip;
	arg.port = port;
	if (clnt_call (clnt, join, (xdrproc_t) xdr_join_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
leave_1(char *ip, int port,  CLIENT *clnt)
{
	leave_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ip = ip;
	arg.port = port;
	if (clnt_call (clnt, leave, (xdrproc_t) xdr_leave_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
subscribe_1(char *ip, int port, char *article,  CLIENT *clnt)
{
	subscribe_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ip = ip;
	arg.port = port;
	arg.article = article;
	if (clnt_call (clnt, subscribe, (xdrproc_t) xdr_subscribe_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
unsubscribe_1(char *ip, int port, char *article,  CLIENT *clnt)
{
	unsubscribe_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ip = ip;
	arg.port = port;
	arg.article = article;
	if (clnt_call (clnt, unsubscribe, (xdrproc_t) xdr_unsubscribe_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
publish_1(char *ip, int port, char *article,  CLIENT *clnt)
{
	publish_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.ip = ip;
	arg.port = port;
	arg.article = article;
	if (clnt_call (clnt, publish, (xdrproc_t) xdr_publish_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
ping_1(CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	 if (clnt_call (clnt, ping, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
